# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df11efc0e0e943a198aa71507c0384d5498966abaad4dcfb82d2476c02eb488939d13f64074f4e9c6a76ef6561e36eec6b2c3bc8f94ff1a309c24e7177d911b

test:
  secret_key_base: 5797f97af2f8830b28166722d32cd967a9034ec1f1c8ab7a57a570b26c45ed1f4dd289f3fb83b0dd4cbd67789b4d02bfd737d6d45f6b8f0870b7a3649f8965ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
